services:
    rvalin.translation.translation_listener:
        class: RValin\TranslationBundle\Listener\TranslationKernelListener
        arguments: ['@translator', "%rvalin_translation.edit.content_editable%"]
        tags:
            - { name: kernel.event_listener, event: kernel.response }
    rvalin.translation.translation_extension:
        class: RValin\TranslationBundle\Twig\TranslationExtension
        arguments: ['@translator', '@router', '%rvalin_translation.edit.textarea%']
        tags:
            - { name: twig.extension }

    rvalin.translation.updaters:
        class: RValin\TranslationBundle\Updater\Updaters

    rvalin.translation.updater.file:
        class: RValin\TranslationBundle\Updater\FileUpdater
        arguments: ['@kernel', '@translation.reader', '@service_container', '%rvalin_translation.allowed_bundles%', '%rvalin_translation.dumpers_config%']
        tags:
            - { name: rvalin.translation.updater, alias: 'file' }

    rvalin.translation.updater.lexik_translation:
        class: RValin\TranslationBundle\Updater\LexikTranslationUpdater
        arguments: ['@lexik_translation.translation_storage', '@lexik_translation.trans_unit.manager']
        tags:
            - { name: rvalin.translation.updater, alias: 'lexik_translation' }