services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    RValin\TranslationBundle\Listener\TranslationKernelListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response }
            - { name: kernel.event_listener, event: kernel.request }


    RValin\TranslationBundle\Updater\FileUpdater:
        tags:
            - { name: rvalin.translation.updater, alias: 'file' }

    RValin\TranslationBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Translation}'

    translator: '@RValin\TranslationBundle\Translation\Translator'